### ISSUE TITLE
Fork origin

### ISSUE THREAD

**Issue by BananaLoaf** [dahlia-os/zircon-rpi#1]
What is the fork origin? I would like to study code changes.

**Comment by nobody5050** [comment]
I think it’s in fuchsia git. This is a fork to support raspberry pi tho

**Comment by BananaLoaf** [comment]
Sorry, I mean the exact commit

**Comment by carbonatedcaffeine** [comment]
Zircon has been updated from the official fuchsia repos.

the commit it was updated with is: 7f21bf635c59a6062ebbb4011ffef7745513f458

I hope this helps @BananaLoaf.

**Comment by nmcain** [comment]
Seems to be ok.
